apiVersion : apps/v1
kind: Deployment
metadata:
  name: js-docker-test 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-docker-test
  template:
    metadata:
      labels:
        app: js-docker-test 
    spec:
      containers:
        - name: js-docker-test 
          image: gammondev.azurecr.io/js-docker-test
          ports:
          - containerPort: 8080